version: '3'

services:
  
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: challenge
      MYSQL_USER: workana
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - challenge
  
  php: 
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: php
    volumes: 
      - ./backend/:/var/www
    ports: 
      - "9000:9000"
    networks: 
      - challenge
  
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8081:81"
    volumes: 
      - ./backend/:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - challenge
    
  backend_node:
    image: "node:12"
    volumes:
      - "./backend_node/:/home/node/app"
    expose:
      - "8082"
    command: bash -c "npm ci && npm run serve"
    working_dir: /home/node/app
    ports:
      - 8082:8082
    links:
      - redis
    depends_on:
      - redis
    networks:
      - challenge

  frontend:
    image: "node:12"
    volumes:
      - "./frontend/:/home/node/app"
    expose:
      - "8080"
    command: bash -c "npm ci && npm run serve"
    working_dir: /home/node/app
    ports:
      - 8080:8080
    depends_on:
      - backend_node
    networks:
      - challenge

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/data
    networks:
      - challenge


networks:
  challenge:

volumes:
  redis:

